# Add configuration values here, as shown below.

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

vb_address: 'http://172.20.10.5:3000'
vb_address_cable: 'ws://172.20.10.5:3000/cable'
vb_ip: '172.20.10.5'
vb_port: '3000'

ftp_host: '172.20.10.4'
ftp_port: 21
ftp_user: 'tom'
ftp_passwd: '1'
ftp_folder: 'projects/upload'
ftp_url: "http://172.20.10.4/"
ftp_passive: true 